apiVersion: v1
kind: ConfigMap
metadata:
  name: envelop-configmap
  namespace: app
  annotations:
    kubernetes-fleet.io/envelope-configmap: "true"
data:
  resourceQuota.yaml: |
    apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: mem-cpu-demo
      namespace: app
    spec:
      hard:
        requests.cpu: "2"
        requests.memory: 2Gi
        limits.cpu: "4"
        limits.memory: 4Gi
