apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: guard
webhooks:
  - name: guard.example.com
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    clientConfig:
      service:
        name: guard
        namespace: ops
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
