apiVersion: v1
entries:
  hub-agent:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-07-07T00:21:28.484864679Z"
    description: A Helm chart for hub agent
    digest: 38839bfbecfc904ff82140d0255718a08f880bec6210dc2bbecf4e923d2b05fa
    name: hub-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-07-07T00:21:28.485363458Z"
    description: Helm chart for member agent.
    digest: a0975283b81fd548817300852eac59dfe38a896bfa703ad572e9dac480e39ef6
    name: member-agent
    type: application
    urls:
    - https://kubefleet-dev.github.io/kubefleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2025-07-07T00:21:28.481267993Z"
