apiVersion: placement.kubernetes-fleet.io/v1alpha1
kind: ResourceOverride
metadata:
  name: metric-app-override
  namespace: test-ns
spec:
  placement:
    name: sample-metric-app
  resourceSelectors:
    - group: apps
      version: v1
      kind: Deployment
      name: sample-metric-app
  policy:
    overrideRules:
      # Override for kind-cluster-1
      - clusterSelector:
          clusterSelectorTerms:
            - labelSelector:
                matchLabels:
                  cluster-name: kind-cluster-1
        jsonPatchOverrides:
          - op: replace
            path: /spec/template/spec/containers/0/env/0/value
            value: "kind-cluster-1"
          - op: replace
            path: /spec/template/spec/containers/0/env/1/value
            value: "sample-metric-app-cluster-1"
      
      # Override for kind-cluster-2
      - clusterSelector:
          clusterSelectorTerms:
            - labelSelector:
                matchLabels:
                  cluster-name: kind-cluster-2
        jsonPatchOverrides:
          - op: replace
            path: /spec/template/spec/containers/0/env/0/value
            value: "kind-cluster-2"
          - op: replace
            path: /spec/template/spec/containers/0/env/1/value
            value: "sample-metric-app-cluster-2"
      
      # Override for kind-cluster-3
      - clusterSelector:
          clusterSelectorTerms:
            - labelSelector:
                matchLabels:
                  cluster-name: kind-cluster-3
        jsonPatchOverrides:
          - op: replace
            path: /spec/template/spec/containers/0/env/0/value
            value: "kind-cluster-3"
          - op: replace
            path: /spec/template/spec/containers/0/env/1/value
            value: "sample-metric-app-cluster-3"
