apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: sample-metric-app
spec:
  resourceSelectors:
    - group: ""
      version: v1
      kind: Namespace
      name: test-ns
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRole
      name: prometheus
    - group: "rbac.authorization.k8s.io"
      version: v1
      kind: ClusterRoleBinding
      name: prometheus
    - group: "placement.kubernetes-fleet.io"
      version: v1beta1
      kind: MetricCollector
      name: sample-app-collector
      namespace: test-ns
  policy:
    placementType: PickAll
  strategy:
    type: RollingUpdate
