apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: crp-1
spec:
  resourceSelectors:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: testresources.test.kubernetes-fleet.io
      version: v1
  policy:
    placementType: PickN
  strategy:
    type: RollingUpdate