apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: crp-7
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      name: my-namespace
      version: v1
  policy:
    placementType: PickAll
  strategy:
    type: RollingUpdate
    applyStrategy:
      allowCoOwnership: true