# MetricCollector - Runs on Member Cluster
# This collects workload_health metrics from Prometheus running on the member cluster
# The controller queries Prometheus every 30 seconds and updates the status with collected metrics

apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: MetricCollector
metadata:
  name: sample-app-collector
  namespace: test-ns
spec:
  # URL of the Prometheus server in the cluster
  # This Prometheus instance scrapes metrics from pods with prometheus.io/* annotations
  prometheusUrl: http://prometheus.test-ns.svc.cluster.local:9090
