# MetricCollectorReport - Created by MetricCollector controller on Hub Cluster
# This report is automatically synced by the MetricCollector controller when it reconciles
# a MetricCollector on the member cluster.
#
# Controller workflow:
# 1. MetricCollector reconciles and collects metrics from Prometheus on member cluster
# 2. Metrics include clusterName label (e.g., cluster-1) from workload_health metric
# 3. Controller extracts clusterName from CollectedMetrics[0].ClusterName
# 4. Controller creates/updates MetricCollectorReport on hub in fleet-member-{clusterName} namespace
# 5. All metrics are guaranteed to have the same clusterName
#
# Namespace: fleet-member-{clusterName} (e.g., fleet-member-cluster-1)
# Name: Same as MetricCollector name (e.g., sample-app-collector)
# Labels: Optional, can be used to track source MetricCollector

apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: MetricCollectorReport
metadata:
  name: sample-app-collector
  namespace: fleet-member-cluster-1
  labels:
    metriccollector-name: sample-app-collector
    metriccollector-namespace: test-ns

# All fields below are synced from MetricCollector status by the controller
conditions:
  - type: MetricCollectorReady
    status: "True"
    reason: CollectorReady
    message: Metric collector is ready and collecting metrics
    lastTransitionTime: "2025-11-20T01:45:00Z"
  - type: MetricsCollecting
    status: "True"
    reason: Collecting
    message: Successfully collecting metrics from Prometheus
    lastTransitionTime: "2025-11-20T01:45:00Z"
observedGeneration: 1
workloadsMonitored: 1
lastCollectionTime: "2025-11-20T01:45:00Z"
collectedMetrics:
  - namespace: test-ns
    clusterName: cluster-1  # All metrics have the same clusterName
    workloadName: sample-metric-app
    health: true
lastReportTime: "2025-11-20T01:45:05Z"
